### ISSUE TITLE
#001

### ISSUE THREAD

**Issue by phmiranda** [SouJavaBrasilia/Comunidade#1]
Boa tarde, gostaria de saber se é possível contribuir no desenvolvimento de uma nova versão do website da comunidade, sistemas que ajudem a manter uma organização automatizada,etc. Existe essa iniciativa atualmente, além de um dia ministrar algum tema.

**Comment by rafabene** [comment]
Oi @phmiranda . Obrigado. Existe já uma iniciativa para o SouJava nacional. Você pode acompanhar o andamento neste documento: https://docs.google.com/document/d/1i2xJJMZSIxIrJ6MXkplDQ1imBpu04Vef18k3UiMLbiw/edit#heading=h.ofuxwpr7ciy - Aliás, você é convidado a ajudar. Chama o Fernando Arruda lá no Slack ;) Abraços. Vou fechar esta issue, ok?
